services:
  db:
    image: postgres:16
    container_name: zero_waste_db
    environment:
      POSTGRES_USER: admdignames
      POSTGRES_PASSWORD: 6RG:*T?Aayq61a5ZFFM%
      POSTGRES_DB: zero_waste
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    build: .
    container_name: zero_waste_backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: